/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as FAQRouteImport } from './routes/faq'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const ServicesRoute = ServicesRouteImport.update({ id: '/services', path: '/services', getParentRoute: () => rootRouteImport } as any)
const AppointmentsRoute = AppointmentsRouteImport.update({ id: '/appointments', path: '/appointments', getParentRoute: () => rootRouteImport } as any)
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport } as any)
const ClinicRoute = ClinicRouteImport.update({ id: '/clinic', path: '/clinic', getParentRoute: () => rootRouteImport } as any)
const FAQRoute = FAQRouteImport.update({ id: '/faq', path: '/faq', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/clinic': typeof ClinicRoute
  '/faq': typeof FAQRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/clinic': typeof ClinicRoute
  '/faq': typeof FAQRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/services' | '/appointments' | '/contact' | '/clinic' | '/faq'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/services' | '/appointments' | '/contact' | '/clinic' | '/faq'
  id: '__root__' | '/' | '/about' | '/services' | '/appointments' | '/contact' | '/clinic' | '/faq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ServicesRoute: typeof ServicesRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ContactRoute: typeof ContactRoute
  ClinicRoute: typeof ClinicRoute
  FAQRoute: typeof FAQRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/about': { id: '/about'; path: '/about'; fullPath: '/about'; preLoaderRoute: typeof AboutRouteImport; parentRoute: typeof rootRouteImport }
    '/services': { id: '/services'; path: '/services'; fullPath: '/services'; preLoaderRoute: typeof ServicesRouteImport; parentRoute: typeof rootRouteImport }
    '/appointments': { id: '/appointments'; path: '/appointments'; fullPath: '/appointments'; preLoaderRoute: typeof AppointmentsRouteImport; parentRoute: typeof rootRouteImport }
    '/contact': { id: '/contact'; path: '/contact'; fullPath: '/contact'; preLoaderRoute: typeof ContactRouteImport; parentRoute: typeof rootRouteImport }
    '/clinic': { id: '/clinic'; path: '/clinic'; fullPath: '/clinic'; preLoaderRoute: typeof ClinicRouteImport; parentRoute: typeof rootRouteImport }
    '/faq': { id: '/faq'; path: '/faq'; fullPath: '/faq'; preLoaderRoute: typeof FAQRouteImport; parentRoute: typeof rootRouteImport }
  }
}
const rootRouteChildren: RootRouteChildren = {
  IndexRoute, AboutRoute, ServicesRoute, AppointmentsRoute, ContactRoute, ClinicRoute, FAQRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
